apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range .Values.secrets }}
  {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}